/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    Dialog: typeof import('primevue/dialog')['default']
    Galleria: typeof import('primevue/galleria')['default']
    Home: typeof import('./../Pages/Home.vue')['default']
    Isabella: typeof import('./../Pages/Isabella.vue')['default']
    Navbar: typeof import('./../Components/Navbar.vue')['default']
    ProductDetails: typeof import('./../Components/ProductDetails.vue')['default']
    Products: typeof import('./../Components/Products.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShareDialog: typeof import('./../Components/ShareDialog.vue')['default']
    TabPanel: typeof import('primevue/tabpanel')['default']
    TabView: typeof import('primevue/tabview')['default']
    Toolbar: typeof import('primevue/toolbar')['default']
  }
}
